name: Soiler
main: net.pravian.soiler.Soiler
version: 2.0
description: Automatic seeding with a command
authors: [Prozza]
commands:
  soil:
    description: Set automatic soiler
    usage: /<command> <wheat | potato | carrot | random | off>